name: lint
on:
  manual: true

jobs:
  clippy:
    steps:
      - name: Run clippy
        uses: bash/exec
        with:
          command: cargo clippy -- -D warnings

  fmt-check:
    steps:
      - name: Check formatting
        uses: bash/exec
        with:
          command: cargo fmt --check
